# 雷霆遗迹 1.21.1 NeoForge 开发配置。
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=thunderrelics
mod_name=Thunder Relics
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=org.hp.thunderrelics
mod_authors=HP
mod_description=Adds the Thunder King creature and its GeckoLib animations.

geckolib_version_range=[4.9.2,5)
